// <auto-generated />
using System;
using System.Reflection;
using DigitalTwin.Mobile.Domain.Enums;
using DigitalTwin.Mobile.Domain.Models;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DigitalTwin.Mobile.Infrastructure.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class EnvironmentReadingEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "DigitalTwin.Mobile.Domain.Models.EnvironmentReading",
                typeof(EnvironmentReading),
                baseEntityType,
                propertyCount: 15,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(EnvironmentReading).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var airQuality = runtimeEntityType.AddProperty(
                "AirQuality",
                typeof(AirQualityLevel),
                propertyInfo: typeof(EnvironmentReading).GetProperty("AirQuality", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<AirQuality>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            airQuality.SetSentinelFromProviderValue(0);

            var aqiIndex = runtimeEntityType.AddProperty(
                "AqiIndex",
                typeof(int),
                propertyInfo: typeof(EnvironmentReading).GetProperty("AqiIndex", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<AqiIndex>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var humidity = runtimeEntityType.AddProperty(
                "Humidity",
                typeof(double),
                propertyInfo: typeof(EnvironmentReading).GetProperty("Humidity", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<Humidity>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var isDirty = runtimeEntityType.AddProperty(
                "IsDirty",
                typeof(bool),
                propertyInfo: typeof(EnvironmentReading).GetProperty("IsDirty", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<IsDirty>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: false);

            var latitude = runtimeEntityType.AddProperty(
                "Latitude",
                typeof(double),
                propertyInfo: typeof(EnvironmentReading).GetProperty("Latitude", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<Latitude>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var locationDisplayName = runtimeEntityType.AddProperty(
                "LocationDisplayName",
                typeof(string),
                propertyInfo: typeof(EnvironmentReading).GetProperty("LocationDisplayName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<LocationDisplayName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 200);

            var longitude = runtimeEntityType.AddProperty(
                "Longitude",
                typeof(double),
                propertyInfo: typeof(EnvironmentReading).GetProperty("Longitude", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<Longitude>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var nO2 = runtimeEntityType.AddProperty(
                "NO2",
                typeof(double),
                propertyInfo: typeof(EnvironmentReading).GetProperty("NO2", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<NO2>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var o3 = runtimeEntityType.AddProperty(
                "O3",
                typeof(double),
                propertyInfo: typeof(EnvironmentReading).GetProperty("O3", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<O3>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var pM10 = runtimeEntityType.AddProperty(
                "PM10",
                typeof(double),
                propertyInfo: typeof(EnvironmentReading).GetProperty("PM10", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<PM10>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var pM25 = runtimeEntityType.AddProperty(
                "PM25",
                typeof(double),
                propertyInfo: typeof(EnvironmentReading).GetProperty("PM25", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<PM25>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var syncedAt = runtimeEntityType.AddProperty(
                "SyncedAt",
                typeof(DateTime?),
                propertyInfo: typeof(EnvironmentReading).GetProperty("SyncedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<SyncedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var temperature = runtimeEntityType.AddProperty(
                "Temperature",
                typeof(double),
                propertyInfo: typeof(EnvironmentReading).GetProperty("Temperature", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<Temperature>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var timestamp = runtimeEntityType.AddProperty(
                "Timestamp",
                typeof(DateTime),
                propertyInfo: typeof(EnvironmentReading).GetProperty("Timestamp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(EnvironmentReading).GetField("<Timestamp>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { timestamp });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "EnvironmentReadings");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
