// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DigitalTwin.Mobile.Infrastructure.Data.CompiledModels
{
    public partial class MobileDbContextModel
    {
        private MobileDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("26cc0bc1-53fe-482c-aa15-1a167015bc82"), entityTypeCount: 9)
        {
        }

        partial void Initialize()
        {
            var chatMessage = ChatMessageEntityType.Create(this);
            var environmentReading = EnvironmentReadingEntityType.Create(this);
            var medicalHistoryEntry = MedicalHistoryEntryEntityType.Create(this);
            var medication = MedicationEntityType.Create(this);
            var ocrDocument = OcrDocumentEntityType.Create(this);
            var patient = PatientEntityType.Create(this);
            var sleepSession = SleepSessionEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var vitalSign = VitalSignEntityType.Create(this);

            ChatMessageEntityType.CreateAnnotations(chatMessage);
            EnvironmentReadingEntityType.CreateAnnotations(environmentReading);
            MedicalHistoryEntryEntityType.CreateAnnotations(medicalHistoryEntry);
            MedicationEntityType.CreateAnnotations(medication);
            OcrDocumentEntityType.CreateAnnotations(ocrDocument);
            PatientEntityType.CreateAnnotations(patient);
            SleepSessionEntityType.CreateAnnotations(sleepSession);
            UserEntityType.CreateAnnotations(user);
            VitalSignEntityType.CreateAnnotations(vitalSign);

            AddAnnotation("ProductVersion", "10.0.3");
        }
    }
}
