// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace DigitalTwin.Mobile.Infrastructure.Data.CompiledModels
{
    public partial class MobileDbContextModel
    {
        private MobileDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("ca69a260-73ae-4e0e-8635-7bbf3a7a60b4"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var patient = PatientEntityType.Create(this);
            var user = UserEntityType.Create(this);
            var vitalSign = VitalSignEntityType.Create(this);

            PatientEntityType.CreateAnnotations(patient);
            UserEntityType.CreateAnnotations(user);
            VitalSignEntityType.CreateAnnotations(vitalSign);

            AddAnnotation("ProductVersion", "10.0.3");
        }
    }
}
